### ISSUE TITLE
Perfect AI friend

### ISSUE THREAD

**Issue by odorizzioficial** [fal-ai/sdxl-lightning-demo-app#2]
Can I put a video about it on my channel friend and leave the link to your GitHub for people to know and use? will it still be free?

**Comment by isidentical** [comment]
@odorizzioficial this is a limited time demo featuring our real-time offering, but in general we recommend using our platform directly (https://fal.ai/models/stable-diffusion-xl-lightning), which every account starts with 10$s (assuming they are in our target audience) ~= almost 10000 pictures.

**Comment by odorizzioficial** [comment]
ah, ok, thank-you
