### ISSUE TITLE
It does not work after issuing "npm run dev"

### ISSUE THREAD

**Issue by z3rotto** [fal-ai/sdxl-lightning-demo-app#6]
This is the log error I got on CMD windows 10.

"
> @fal-ai/sdxl-lightning@0.1.0 dev
> next dev

"next" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
"

**Comment by aykutkardas** [comment]
Before running the `npm run dev` command, are you sure that you have installed the dependencies?

You can run the following commands in order.
`npm install`
`npm run dev`

**Comment by z3rotto** [comment]
Thank you! I forgot about it...
